services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Substituting username from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Password substitution from .env
    networks:
      - projects-network
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    name: postgres-data

networks:
  projects-network:
    name: projects-network
    external: true
